apiVersion: v1
kind: PersistentVolume
metadata:
  name: openedx-media-efs
  labels:
    app.kubernetes.io/name: openedx-media
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-openedx-media
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "__EFS_FILE_SYSTEM_ID__::__EFS_ACCESS_POINT_ID__"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openedx-media
  namespace: openedx-prod
  labels:
    app.kubernetes.io/name: openedx-media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-openedx-media
  volumeName: openedx-media-efs
  resources:
    requests:
      storage: 20Gi
