apiVersion: v1
kind: Pod
metadata:
  name: pvc-test
  namespace: openedx-prod
spec:
  containers:
  - name: alpine
    image: alpine:3.20
    command: ["sh", "-c", "echo 'bismillah storage works' > /data/ok.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: openedx-media
